# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Orange & Bronze Software Labs, Inc. | Software Development
email: info@orangeandbronze.com
contact_number: (63) 2 8894-3415
contact_number_2: (63) 2 8478-9999
address: "Philippines: 3rd Floor, CJV Building
108 Aguirre Street, Legaspi Village, 
Makati City, Philippines 1229"
keywords: software development philippines, java philippines, java developer philippines, software offshoring philippines, managed agile, devops teams,  gsuite and goolge cloud partner philippines, google workspace, outsourced software development philippines, software offshoring, java consulting philippines, java company philippines, java offshore philippines, java outsource philippines, java outsourcing philippines, java development philippines, java software philippines, java software development philippines, agile development philippines, spring developers philippines, spring outsourcing philippines, spring offshore philippines, java developer outsourcing philippines, java programming training philippines, software offshoring philippines
description: We develop mission-critical systems using the Spring Framework, handling millions of transactions for companies.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://orangeandbronze.com" the base hostname & protocol for your site, e.g. http://example.com
facebook_username: orangeandbronze
googleplus_username: +orangeandbronze
twitter_username: "@orangeandbronze"
linkedin_username:  orange-and-bronze-software-labs
safe: false

plugins: 
   - jekyll-redirect-from
   - jekyll-seo-tag
   - jekyll-paginate-v2

permalink: pretty
permalink: /:categories/:title/

defaults:
  - scope:
      path: 'blogs/_posts'
      type: posts
    values:
      permalink: /blogs/:year/:month/:title
      category: blogs

# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true
  tags:
    layouts:
      - autopage-blogs-by-tags.html
    title: ':tag | Orange Orchard'
    permalink: '/tags/:tag'
    enabled: true
  categories:
    enabled: false
  collections:
    enabled: false

# Build settings
markdown: kramdown

header_pages:
 - work.html
 - services.html
 - trainings.html
 - about.html
 - careers.html
 - /blogs/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
